# In this directory, run the following command to build this builder.
# $ gcloud alpha container builds create . --config=cloudbuild.yaml

steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--pull', '--tag=gcr.io/$PROJECT_ID/gsutil', '.']
- name: 'gcr.io/$PROJECT_ID/gsutil'
  args: ['version']

images: ['gcr.io/$PROJECT_ID/gsutil']
