# In this directory, run the following command to build this builder.
# $ gcloud container builds submit . --config=cloudbuild.yaml

steps:
# Pull the latest go image.
- name: 'gcr.io/cloud-builders/docker'
  args: ['pull', 'gcr.io/cloud-builders/go']
- name: 'gcr.io/cloud-builders/go'
  args: ['install', 'golang_project']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--pull', '--tag=gcr.io/$PROJECT_ID/golang-project', '.']

# Test the examples.

# examples/hello_world
- name: 'gcr.io/$PROJECT_ID/golang-project'
  args: ['hello', '--tag=hello_world']
  dir: 'examples/hello_world'

# examples/multi_bin
- name: 'gcr.io/$PROJECT_ID/golang-project'
  args:
  - 'product/server'
  - 'product/subtool'
  - 'product/subtool/subpkg'
  - '--entrypoint=server'
  - '--tag=gcr.io/$PROJECT_ID/golang_project_multi_bin'
  env: ['PROJECT_ROOT=product']
  dir: 'examples/multi_bin'

# examples/static_webserver
- name: 'gcr.io/$PROJECT_ID/golang-project'
  args: ['server', '--tag=server_intermediate']
  dir: 'examples/static_webserver'
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=server', '.']
  dir: 'examples/static_webserver'

# examples/custom_base
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=alpine-cacerts', '-f', 'Dockerfile.cacerts', '.']
  dir: 'examples/custom_base'
- name: 'gcr.io/$PROJECT_ID/golang-project'
  args: ['client', '--base-image=alpine-cacerts', '--tag=gcr.io/$PROJECT_ID/golang_project_custom_base']
  dir: 'examples/custom_base'


images: ['gcr.io/$PROJECT_ID/golang-project']
